/// <reference types="vite/client" />

// Generated by the carouselImagesPlugin in vite.config.ts — lists image
// files found in public/images/carousel/ at dev/build time, for the admin
// banner picker (src/pages/AdminPage.tsx).
declare module 'virtual:carousel-images' {
  const images: string[];
  export default images;
}
